[supervisord]
nodaemon=true
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/run/gcforms/supervisord.pid

[program:postgres]
command=/opt/gcforms/omnibus/bin/run-postgres.sh
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:redis]
command=/opt/gcforms/omnibus/bin/run-redis.sh
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:localstack]
command=/opt/gcforms/omnibus/bin/run-localstack.sh
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:local-idp]
command=/opt/gcforms/omnibus/bin/run-local-idp.sh
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:bootstrap]
command=/opt/gcforms/omnibus/bin/bootstrap.sh
autorestart=false
startsecs=0
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:forms-api]
command=/opt/gcforms/omnibus/bin/run-api.sh
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:forms-client]
command=/opt/gcforms/omnibus/bin/run-client.sh
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
